export const API_V1 = {
  auth: {
    login: '/api/v1/auth/login',
    logout: '/api/v1/auth/logout',
    me: '/api/v1/auth/me',
  },
  me: {
    profile: '/api/v1/me/profile',
    terms: '/api/v1/me/terms',
    todayClass: '/api/v1/me/today-class',
    academicSummary: '/api/v1/me/academic/summary',
    financialSummary: '/api/v1/me/financial/summary',
    financialInvoices: '/api/v1/me/financial/invoices',
    notifications: '/api/v1/me/notifications',
    unreadCount: '/api/v1/me/notifications/unread-count',
    documents: '/api/v1/me/documents',
    documentRequest: (docType: string) => `/api/v1/me/documents/${docType}/request`,
    documentDownload: (docType: string) => `/api/v1/me/documents/${docType}/download`,
    // New endpoints
    scheduleToday: '/api/v1/me/schedule/today',
    scheduleWeek: '/api/v1/me/schedule/week',
    enrollments: '/api/v1/me/enrollments',
    grades: '/api/v1/me/grades',
    attendance: '/api/v1/me/attendance',
    transcript: '/api/v1/me/transcript',
  },
  admin: {
    users: '/api/v1/admin/users',
    terms: '/api/v1/admin/terms',
    generateSessions: (termId: string) => `/api/v1/admin/terms/${termId}/generate-sessions`,
    courses: '/api/v1/admin/courses',
    subjects: '/api/v1/admin/subjects',
    sections: '/api/v1/admin/sections',
    sectionMeetings: (sectionId: string) => `/api/v1/admin/sections/${sectionId}/meetings`,
    meeting: (meetingId: string) => `/api/v1/admin/meetings/${meetingId}`,
    sectionSessions: (sectionId: string) => `/api/v1/admin/sections/${sectionId}/sessions`,
    session: (sessionId: string) => `/api/v1/admin/sessions/${sessionId}`,
    students: '/api/v1/admin/students',
    enrollments: '/api/v1/admin/enrollments',
    enrollment: (enrollmentId: string) => `/api/v1/admin/enrollments/${enrollmentId}`,
    attendance: '/api/v1/admin/attendance',
    attendanceItem: (attendanceId: string) => `/api/v1/admin/attendance/${attendanceId}`,
    assessments: '/api/v1/admin/assessments',
    assessment: (assessmentId: string) => `/api/v1/admin/assessments/${assessmentId}`,
    assessmentGrades: '/api/v1/admin/assessment-grades',
    assessmentGrade: (gradeId: string) => `/api/v1/admin/assessment-grades/${gradeId}`,
    finalGrades: '/api/v1/admin/final-grades',
    finalGrade: (gradeId: string) => `/api/v1/admin/final-grades/${gradeId}`,
    invoices: '/api/v1/admin/invoices',
    invoice: (invoiceId: string) => `/api/v1/admin/invoices/${invoiceId}`,
    markInvoicePaid: (invoiceId: string) => `/api/v1/admin/invoices/${invoiceId}/mark-paid`,
    payments: '/api/v1/admin/payments',
    payment: (paymentId: string) => `/api/v1/admin/payments/${paymentId}`,
    notifications: '/api/v1/admin/notifications',
    notification: (id: string) => `/api/v1/admin/notifications/${id}`,
    deliverNotification: (id: string) => `/api/v1/admin/notifications/${id}/deliver`,
    userNotifications: '/api/v1/admin/user-notifications',
    notificationPreferences: (userId: string) => `/api/v1/admin/users/${userId}/notification-preferences`,
    studentDocuments: '/api/v1/admin/student-documents',
    studentDocument: (docId: string) => `/api/v1/admin/student-documents/${docId}`,
    dashboard: {
      terms: '/api/v1/admin/dashboard/terms',
      stats: '/api/v1/admin/dashboard/stats',
    },
  },
} as const;

